version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm run build:dev
      - run: npm run test

  build-minified:
    docker:
      - image: circleci/node:9.2.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: "Install dependencies"
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: "Create minified version artifact"
          command: |
            npm run build:prod
            zip -r arch$(date +"%Y%m%d_%H%M%S").zip build
            mkdir /tmp/build_artifacts
            mv arch*.zip /tmp/build_artifacts
      - store_artifacts:
          path: /tmp/build_artifacts
workflows:
  version: 2
  main:
    jobs:
      - build

  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
                - ci-nightly
    jobs:
      - build-minified
