version: 2
jobs:
  build-dev:
    docker:
      - image: circleci/node:9.2.1

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm run build:dev
      - run: npm run test

  build-minified:
    docker:
      - image: circleci/node:9.2.1

    working_directory: /tmp

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          command: |
            npm run build:prod
            zip -r arch$(date +"%Y%m%d_%H%M%S").zip build